<a href="https://colab.research.google.com/github/AarifSheikh-78603/Computer-Vision-Deep-Learning/blob/main/4_Build_a_Deep_Neural_Network_Step_by_Step_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import h5py
import matplotlib.pyplot as plt
#from testCases import *
#from dnn_utils import sigmoid, sigmoid_backward, relu, relu_backward
#from public_tests import *

%matplotlib inline
plt.rcParams['figure.figsize'] = (5.0, 4.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'
%load_ext autoreload
%autoreload 2
np.random.seed(1)


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
# Here we can creat first function this function has initilaze parameters
def initialize_parameters(n_x, n_h, n_y):

 np.random.seed(1)
 W1=np.random.randn(n_h,n_x)*0.01
 b1=np.zeros(shape=(n_h,1))
 W2=np.random.randn(n_y,n_h)*0.01
 b2=np.zeros(shape=(n_y,1))
 parameters = {"W1": W1,"b1": b1,"W2": W2,"b2": b2}
 return parameters
parameters = initialize_parameters(3,2,1)
print("**************************************")
print("W1 = " + str(parameters["W1"]))
print("**************************************")
print("b1 = " + str(parameters["b1"]))
print("**************************************")
print("W2 = " + str(parameters["W2"]))
print("**************************************")
print("b2 = " + str(parameters["b2"]))

**************************************
W1 = [[ 0.01624345 -0.00611756 -0.00528172]
 [-0.01072969  0.00865408 -0.02301539]]
**************************************
b1 = [[0.]
 [0.]]
**************************************
W2 = [[ 0.01744812 -0.00761207]]
**************************************
b2 = [[0.]]


In [ ]:
# GRADED FUNCTION: initialize_parameters_deep
def initialize_parameters_deep(layer_dims):

 np.random.seed(3)
 parameters = {}
 L = len(layer_dims) # number of layers in the network
 for l in range(1, L):
  parameters['W' + str(l)] = np.random.randn(layer_dims[l],layer_dims[l-1])*0.01
  parameters['b' + str(l)] = np.zeros((layer_dims[l],1))
 assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l - 1]))
 assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))
 return parameters
parameters = initialize_parameters_deep([5,4,3])
print("**************************************")
print("W1 = " + str(parameters["W1"]))
print("**************************************")
print("b1 = " + str(parameters["b1"]))
print("**************************************")
print("W2 = " + str(parameters["W2"]))
print("**************************************")
print("b2 = " + str(parameters["b2"]))

**************************************
W1 = [[ 0.01788628  0.0043651   0.00096497 -0.01863493 -0.00277388]
 [-0.00354759 -0.00082741 -0.00627001 -0.00043818 -0.00477218]
 [-0.01313865  0.00884622  0.00881318  0.01709573  0.00050034]
 [-0.00404677 -0.0054536  -0.01546477  0.00982367 -0.01101068]]
**************************************
b1 = [[0.]
 [0.]
 [0.]
 [0.]]
**************************************
W2 = [[-0.01185047 -0.0020565   0.01486148  0.00236716]
 [-0.01023785 -0.00712993  0.00625245 -0.00160513]
 [-0.00768836 -0.00230031  0.00745056  0.01976111]]
**************************************
b2 = [[0.]
 [0.]
 [0.]]


In [ ]:
# Here we can create the linear function
def linear_forward(A, W, b):
 Z=np.dot(W,A)+b
 cache = (A, W, b)
 return Z, cache


# Here we creat linear_activation_forward
def linear_activation_forward(A_prev, W, b, activation):

 if activation == "sigmoid":
  Z, linear_cache =linear_forward(A_prev,W,b)
  A, activation_cache =sigmoid(Z)

 elif activation == "relu":
  Z, linear_cache = linear_forward(A_prev,W,b)
  A, activation_cache =relu(Z)

 cache = (linear_cache, activation_cache)
 return A, cache


# creat L_model_forward
def L_model_forward(X, parameters):
 caches = []
 A = X
 L = len(parameters) // 2
 for l in range(1, L):
  A_prev = A
  A, cache =linear_activation_forward(A_prev, parameters['W'+str(l)],parameters['b'+str(l)],activation='relu')
 caches.append(cache)

 AL, cache =linear_activation_forward(A,
 parameters['W'+str(L)],parameters['b'+str(L)],activation='sigmoid')
 caches.append(cache)


 #assert(AL.shape == (1, X.shape[1]))
 return AL, caches


In [ ]:
# Creat the function compute_cost
def compute_cost(AL, Y):
 m = Y.shape[1]
 cost = (-1 / m) * np.sum(np.multiply(Y, np.log(AL)) + np.multiply(1 - Y, np.log(1 - AL)))
 cost = np.squeeze(cost)
 return cost
A = np.array([[1, 2], [3, 4]])


# To make sure your cost's shape is what we expect (e.g. this turns [[17]] into 17).
print('axis=1 and keepdims=True')
print(np.sum(A, axis=1, keepdims=True))
print('axis=1 and keepdims=False')
print(np.sum(A, axis=1, keepdims=False))
print('axis=0 and keepdims=True')
print(np.sum(A, axis=0, keepdims=True))
print('axis=0 and keepdims=False')
print(np.sum(A, axis=0, keepdims=False))


axis=1 and keepdims=True
[[3]
 [7]]
axis=1 and keepdims=False
[3 7]
axis=0 and keepdims=True
[[4 6]]
axis=0 and keepdims=False
[4 6]


In [ ]:
# Create the function: linear_backward
def linear_backward(dZ, cache):
 A_prev, W, b = cache
 m = A_prev.shape[1]
 dW = np.dot(dZ, cache[0].T) / m
 db = (1/m)*(np.sum(dZ, axis=1, keepdims=True))
 dA_prev = np.dot(cache[1].T, dZ)
 return dA_prev, dW, db


In [ ]:
# Create the function linear_activation_backward
def linear_activation_backward(dA, cache, activation):
 linear_cache, activation_cache = cache

 if activation == "relu":
  dZ = relu_backward(dA, activation_cache)
  dA_prev, dW, db =linear_backward(dZ, linear_cache)
 elif activation == "sigmoid":
    dZ = sigmoid_backward(dA, activation_cache)
    dA_prev, dW, db = linear_backward(dZ, linear_cache)

 return dA_prev, dW, db

In [ ]:
# Creat Function: L_model_backward
def L_model_backward(AL, Y, caches):
 grads = {}
 L = len(caches) # the number of layers
 m = AL.shape[1]
 Y = Y.reshape(AL.shape) # after this line, Y is the same shape as AL


 # Initializing the backpropagation
 print("L = "+str(L))
 dAL = - (np.divide(Y, AL) - np.divide(1 - Y, 1 - AL))
 current_cache = caches[L-1]
 grads["dA" + str(L-1)], grads["dW" + str(L)], grads["db" + str(L)] = linear_activation_backward(dAL, current_cache,
activation = "sigmoid")
 print("dA"+ str(L-1)+" = "+str(grads["dA" + str(L-1)]))
 print("dW"+ str(L)+" = "+str(grads["dW" + str(L)]))
 print("db"+ str(L)+" = "+str(grads["db" + str(L)]))


 # Loop from l=L-2 to l=0
 for l in reversed(range(L-1)):
  current_cache = caches[l]
  dA_prev_temp, dW_temp, db_temp = linear_activation_backward(grads["dA" + str(l + 1)], current_cache,
activation = "relu")
  grads["dA" + str(l)] = dA_prev_temp
  grads["dW" + str(l + 1)] = dW_temp
  grads["db" + str(l + 1)] = db_temp

 return grads


In [ ]:
# Create The function: update_parameters
def update_parameters(params, grads, learning_rate):
 parameters = params.copy()
 L = len(parameters) // 2 # number of layers in the neural network

 # Update rule for each parameter. Use a for loop.
 for l in range(L):

  parameters["W" + str(l+1)] = parameters["W" + str(l+1)] - learning_rate * grads["dW" + str(l+1)]
  parameters["b" + str(l+1)] = parameters["b" + str(l+1)] - learning_rate * grads["db" + str(l+1)]

 return parameters
def update_parameters(parameters, grads, learning_rate):
 L = len(parameters) // 2 # number of layers in the neural network

# Update rule for each parameter. Use a for loop.
 for l in range(L):
  parameters["W" + str(l+1)] = parameters["W" + str(l+1)] - learning_rate * grads["dW" + str(l+1)]
  parameters["b" + str(l+1)] = parameters["b" + str(l+1)] - learning_rate * grads["db" + str(l+1)]
 return parameters


In [ ]:
print ("W1 = "+ str(parameters["W1"]))
print ("b1 = "+ str(parameters["b1"]))
print ("W2 = "+ str(parameters["W2"]))
print ("b2 = "+ str(parameters["b2"]))

W1 = [[ 0.01788628  0.0043651   0.00096497 -0.01863493 -0.00277388]
 [-0.00354759 -0.00082741 -0.00627001 -0.00043818 -0.00477218]
 [-0.01313865  0.00884622  0.00881318  0.01709573  0.00050034]
 [-0.00404677 -0.0054536  -0.01546477  0.00982367 -0.01101068]]
b1 = [[0.]
 [0.]
 [0.]
 [0.]]
W2 = [[-0.01185047 -0.0020565   0.01486148  0.00236716]
 [-0.01023785 -0.00712993  0.00625245 -0.00160513]
 [-0.00768836 -0.00230031  0.00745056  0.01976111]]
b2 = [[0.]
 [0.]
 [0.]]
